
module.exports.address0x = '0x0000000000000000000000000000000000000000';

module.exports.tryCatchRevert = async (promise, message, headMsg = 'revert ') => {
    if (message === '') {
        headMsg = headMsg.slice(0, headMsg.length - 1);
        console.warn('    \u001b[93m\u001b[2m\u001b[1m⬐ Warning:\u001b[0m\u001b[30m\u001b[1m There is an empty revert/require message');
    }
    try {
        if (promise instanceof Function) {
            await promise();
        } else {
            await promise;
        }
    } catch (error) {
        assert(
            error.message.search(headMsg + message) >= 0 || process.env.SOLIDITY_COVERAGE,
            'Expected a revert \'' + headMsg + message + '\', got \'' + error.message + '\' instead'
        );
        return;
    }
    assert.fail('Expected throw not received');
};
